apiVersion: v1
kind: Service
metadata:
  name: {{ include "axiom-engine.fullname" . }}
  labels:
    {{- include "axiom-engine.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "axiom-engine.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "axiom-engine.fullname" . }}-headless
  labels:
    {{- include "axiom-engine.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    {{- include "axiom-engine.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
    - name: epmd
      port: 4369
      targetPort: epmd
      protocol: TCP
    - name: erlang-dist
      port: 9100
      targetPort: erlang-dist
      protocol: TCP
